version: '2'
services:
  mariadb:
    image: bitnami/mariadb:latest
    environment:
      - MARIADB_USER=bn_moodle
      - MARIADB_PASSWORD=bitnami
      - MARIADB_DATABASE=bitnami_moodle
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      - 'mariadb_data:/bitnami/mariadb'  # Mounts a volume named 'mariadb_data' to store MariaDB data

  moodle:
    image: bitnami/moodle:latest
    ports:
      - '80:80'  # Maps port 80 of the host to port 8080 of the container
      - '443:8443'  # Maps port 443 of the host to port 8443 of the container
    environment:
      - MOODLE_DATABASE_HOST=mariadb  # Specifies the hostname of the MariaDB service
      - MOODLE_DATABASE_PORT_NUMBER=3306  # Specifies the port number of the MariaDB service
      - MOODLE_DATABASE_USER=bn_moodle  # Sets the Moodle database username
      - MOODLE_DATABASE_NAME=moodle  # Sets the Moodle database name
    volumes:
      - 'moodle_data:/bitnami/moodle'  # Mounts a volume named 'moodle_data' to store Moodle application data
      - 'moodledata_data:/bitnami/moodledata'  # Mounts a volume named 'moodledata_data' to store Moodle data
    depends_on:
      - mariadb  # Specifies that the moodle service depends on the mariadb service

volumes:
  mariadb_data:
    driver: local  # Uses the local driver to create the mariadb_data volume
  moodle_data:
    driver: local  # Uses the local driver to create the moodle_data volume
  moodledata_data:
    driver: local  # Uses the local driver to create the moodledata_data volume
